name: 'on wfc npm audit'

on: 
  workflow_call:
    inputs:
      autofix_pr_branch:
        type: string
        description: 'autofix pr branch'
        required: false
        default: 'autofix'
      autofix_pr:
        type: boolean
        description: 'autofix pr'
        required: false
        default: false
      autofix_breaking:
        type: boolean
        description: 'autofix breaking'
        required: false
        default: false

jobs:
  
  audit:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix: 
        context:
          - frontend
          - backend

    steps:
      - 
        uses: actions/checkout@v3    
      - 
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          cache: 'npm'
          cache-dependency-path: ${{ matrix.context }}/package-lock.json
      - 
        name: run audit
        working-directory: ${{ matrix.context }}
        run: |
          npm install
          if [[ "${{ inputs.autofix_pr }}" = "true" ]]; then
            if [[ "${{ inputs.autofix_breaking }}" = "true" ]]; then
              npm audit fix --force
            else
              npm audit fix
            fi
          else
            npm audit
          fi
      - 
        id: pr_vars
        if: ${{ failure() && inputs.autofix_pr }}
        run: |
          pr_title="audit autofix pr"
          pr_branch=${{ inputs.autofix_pr_branch }}-${{ matrix.context }}-audit

          if [[ "${{ inputs.autofix_pr }}" = "true" ]]; then
            if [[ "${{ inputs.autofix_breaking }}" = "true" ]]; then
              pr_title="audit autofix pr (breaking)"
            fi
          fi

          echo "pr_title=$pr_title" >> $GITHUB_OUTPUT
          echo "pr_branch=$pr_branch" >> $GITHUB_OUTPUT
      - 
        name: create audit pr
        if: ${{ failure() && inputs.autofix_pr }}
        id: create_pull_request
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.WORKFLOW_TOKEN }}
          title: ${{ steps.pr_vars.outputs.pr_title }}
          branch: ${{ steps.pr_vars.outputs.pr_branch }}
