name: 'on wfc create tag'

on:
  workflow_call:
    inputs:
      tag:
        type: string
        description: 'tag'
        required: true
jobs:
  create_tag:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - 
        uses: actions/checkout@v3
      - 
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com          
      - 
        run: |      
          git tag ${{ inputs.tag }}
          git push -f origin --tags