name: docker-build-push
on: 
  workflow_call:
    inputs:
      image_tag:
        type: string
        description: 'tag to use for published images'
        required: true

concurrency: 
  group:  docker_build_${{ inputs.image_tag }}
  cancel-in-progress: false

jobs:

  docker-build:

    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      
    strategy:
      fail-fast: true
      matrix: 
        context:
          - frontend
          - backend

    steps:
      - 
        uses: actions/checkout@v3
      - 
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - 
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - 
        name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - 
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ${{ matrix.context }}
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: |
            ghcr.io/${{ github.repository }}/weatherapp_${{ matrix.context }}:${{ inputs.image_tag }}